# -*- coding: utf-8 -*-
"""Atividade 1 Calculadora 1.1 Inclusão Try-Except

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhrlKYegcCA_kPXqgVA6ovIvZPwn26lT
"""

nomeuser = input('Por favor insira seu nome: ')

print(f'Olá, {nomeuser}! Por favor insira dois valores e a operação que deseja realizar')

valor1 = input('Digite o valor: ')
valor2 = input('Digite o valor: ')

try:
    valor1convert = float(valor1)
    valor2convert = float(valor2)

    conta = input('Agora digite a operação que deseja realizar: ')

    if conta == '+':
        resultado = valor1convert + valor2convert
        print(f'O resultado foi: {resultado}')

    elif conta == '-':
        resultado = valor1convert - valor2convert
        print(f'O resultado foi: {resultado}')

    elif conta == '*':
        resultado = valor1convert * valor2convert
        print(f'O resultado foi: {resultado}')

    elif conta == '/':
        resultado = valor1convert / valor2convert
        print(f'O resultado foi: {resultado}')

    elif conta == '**':
        resultado = valor1convert ** valor2convert
        print(f'O resultado foi: {resultado}')

    else:
        print('Desculpe, no momento essa operação não pode ser realizada')
except ValueError:
    print('Entrada inválida. Por favor, insira números válidos para os valores.')